eureka:
  environment: ppr
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URI}

exchange:
  hostname: exst-ui${HOST_NAME_COLOR}-ppr.schneider-electric.com

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

redirect:
  whitelist:
    ${exchange.hostname},
    exst-ui-ppr.schneider-electric.com,
    pprdschneider.appdirect.com,
    ppd-data.exchange.se.com,
    schneider.qmerit.com,
    uat-community.exchange.se.com,
    ecoxpert-qa.dev.se.com,
    pprdschneider.appdirect.com,
    secureidentity-preprod.schneider-electric.com,
    partner.schneider-electric.com,
    godigital-pprod2.dev.schneider-electric.com,
    se--preprod21.my.salesforce.com,
    preprod21-secommunities.cs61.force.com

schneider:
  company:
    channel:
      name: Schneider Electric
      #COMPANY CHANNEL as a prefix for all subscribed channels
      prefix: CC_
      training:
        link: https://schneider-electric3-pilot.csod.com/samldefault.aspx?ouid=3&returnurl=https://schneider-electric3-pilot.csod.com/LMS/LoDetails/DetailsLo.aspx?loid=
        homePageLink: https://schneider-electric3-pilot.csod.com/samldefault.aspx?ouid=3
      opportunity:
        application-name: Exchange
        link: https://preprod21-secommunities.cs61.force.com/opportunities/home#/Opportunity/
