lithium:
  url:
    base: https://uat-community.exchange.se.com
    auth: ${lithium.url.base}/restapi/vc/authentication/sessions/login
    knowledge-base: ${lithium.url.base}/t5/Building-Automation-Knowledge/tkb-p/knowledge-base_public
  board-id: open-forum
  http-url-max-length: 2000

---
spring:
  profiles: local
lithium:
  auth:
    username: #Get local credentials on https://schneider.atlassian.net/wiki/spaces/Exchange/pages/2271151475/Local+profile+credentials
    password:
    basic:
      username:
      password:

---
spring:
  profiles: prod
lithium:
  url:
    base: https://community.exchange.se.com
  board-id: SE-Exchange-Open-Community-forum
