appmarket:
  url:
    base: https://testschneider.appdirect.com
    rest: ${appmarket.url.base}/api
  roles:
    ROLE_SYS_ADMIN: MP_ROLE_COMPANY_ADMIN
    ROLE_BILLING_ADMIN: MP_ROLE_BILLING_ADMIN
    ROLE_DEVELOPER: MP_ROLE_PUBLISHER
  auth:
    access-token-uri: ${appmarket.url.base}/oauth2/token
    scope:
      - ROLE_PARTNER
  idms:
    app-label: AppDirect
    client-id: 8c4105f03f4ceef067df8974109c4113a07592a104609cda3d58b9c4f3a1d68548714c00Dg0000006I2OaEAK
    redirect-uri: ${appmarket.url.base}/oauth2/return
  search:
    product-line-id: 756
  health:
    auth:
      username: health
      password: health
    federated-id: gb004f99-ba64-445d-1432-877d4416ef1e
    company-federated-id: gb008136-e0a6-5d21-0e0c-a8fd0dbbb287
    custom-attribute-name: commercial_registration_id
  product-lead:
    partner: SCHNEIDER
---
spring:
  profiles: sit
appmarket:
  idms:
    client-id: 3MVG9ahGHqp.k2_xWoKZZKzfq3rMAA.f_sOueJHmia9Ua7xK.4NLkf9g4kCQP9nnUASmqgPNFseXzN2DnRfst
---
spring:
  profiles: uat
appmarket:
  url:
    base: https://testschneider2.appdirect.com
  idms:
    client-id: 8c4105f03f4ceef067df8974109c4113a07592a104609cda3d58b9c4f3a1d68548714c00Dg0000006I2OaEAK
  search:
    product-line-id: 744
  product-lead:
    partner: SCHNEIDER2
---
# todo: obtain new client-id and secret for uat2 env
spring:
  profiles: uat2
appmarket:
  url:
    base: https://testschneider2.appdirect.com
  idms:
    client-id: 8c4105f03f4ceef067df8974109c4113a07592a104609cda3d58b9c4f3a1d68548714c00Dg0000006I2OaEAK
  search:
    product-line-id: 744
  product-lead:
    partner: SCHNEIDER2
---
spring:
  profiles: ppr
appmarket:
  url:
    base: https://pprdschneider.appdirect.com
  idms:
    client-id: 3MVG9ahGHqp.k2_zHolxbafgOAH8RH0qsphliDkXIymNTa.dtn1_v8UVg1K.pfMl62J.ToFheiFUgiDs0aPwU
  search:
    product-line-id: 721
  health:
    federated-id: gb006962-f6bb-1165-1e4b-7f07b46ca119
    company-federated-id: gb0066d0-868b-92e9-2f7d-75ee97696d3e
  product-lead:
    partner: SCHNEIDER3
---
spring:
  profiles: prod
appmarket:
  url:
    base: https://shop.exchange.se.com
  idms:
    client-id: 3MVG9yZ.WNe6byQAvlJ.HwD94PWoznDCfj3A_RCJgJD7L4TQrZT6D3FptoCCma0GFmQ6P_PpLIad_CMw1pYfX
  search:
    product-line-id: 55
  health:
    federated-id: gb00da9a-b4de-cf2a-1582-20046aca30a4
    company-federated-id: gb0067d1-fcf9-a1b2-3aad-ebdf1f040118
---
spring:
  profiles: local
appmarket:
  auth:
    client-id: #Get local credentials on https://schneider.atlassian.net/wiki/spaces/Exchange/pages/2271151475/Local+profile+credentials
    client-secret:
