spring:
  mail:
    host: smtp.nonprod.iotdo.schneider-electric.com
    port: 25
mail:
  enable: true
  leads:
    subject: You Have a New Business Lead from Schneider Electric Exchange
    from: no-reply@exchange.schneider-electric.com

---
spring:
  profiles: ppr,prod
  mail:
    host: smtp.prod.iotdo.schneider-electric.com
