eureka:
  environment: prod
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URI}

exchange:
  hostname: exchange${HOST_NAME_COLOR}.se.com

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

redirect:
  whitelist:
    ${exchange.hostname},
    exchange.se.com,
    shop.exchange.se.com,
    schneider.appdirect.de,
    exchangecommunity.schneider-electric.com,
    ecoxpert.se.com,
    data.exchange.se.com,
    serviceprovider.qmerit.com,
    community.exchange.se.com,
    secureidentity.schneider-electric.com,
    partner.schneider-electric.com,
    godigital.schneider-electric.com,
    se.my.salesforce.com

schneider:
  company:
    channel:
      name: Schneider Electric
      #COMPANY CHANNEL as a prefix for all subscribed channels
      prefix: CC_
      training:
        link: https://schneider-electric.csod.com/samldefault.aspx?ouid=7&returnurl=https://schneider-electric.csod.com/LMS/LoDetails/DetailsLo.aspx?loid=
        homePageLink: https://schneider-electric.csod.com/samldefault.aspx?ouid=7
      opportunity:
        application-name: Exchange
        link: https://partner.schneider-electric.com/opportunities/home#/Opportunity/
