idol:
  server:
    port: 8071
  url:
    base: http://10.238.86.189:${idol.server.port}

---
spring:
  profiles: dev3, uat, uat2, ppr
idol:
  url:
    base: http://10.238.86.137:${idol.server.port}
---
spring:
  profiles: prod
idol:
  url:
    base: http://internal-use-alb-search-exst-prod-iso-1811159667.us-east-1.elb.amazonaws.com:${idol.server.port}
