health:
  config:
    enabled: false
management:
  info:
    git:
      mode: full
logging:
  level:
    root: INFO
    com.epam: DEBUG
    com.netflix.discovery: WARN
    com.netflix.discovery.endpoint: ERROR

spring:
  application:
    instance_id: ${server.port}:${random.uuid}
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
    baggage-keys:
      - federatedId
      - companyFederatedId
      - contactId
      - bfoId
    log:
      slf4j:
        whitelisted-mdc-keys:
          - federatedId
          - companyFederatedId
          - contactId
          - bfoId
          - APP_NAME
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    stack:
      auto: false

aws:
  region: eu-west-1
  url: https://s3-eu-west-1.amazonaws.com

eureka:
  environment: local
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    prefer-ip-address: true

exchange:
  hostname: localhost
  url: http://${exchange.hostname}:9001

hystrix.threadpool.default:
  coreSize: 150
  maxQueueSize: 50
  queueSizeRejectionThreshold: 50

redirect:
  whitelist:
    ${exchange.hostname},
    exst-ui-dev.schneider-electric.com,
    testschneider.appdirect.com,
    qa-buildings.schneider-electric.com,
    uat-data.exchange.se.com,
    schneider.qmerit.com,
    uat-community.exchange.se.com,
    ecoxpert-qa.dev.se.com,
    sitbfo19-secommunities.cs17.force.com,
    partner.schneider-electric.com,
    godigital-sqe2.dev.schneider-electric.com,
    se--sitbfo19.my.salesforce.com

schneider:
  company:
    channel:
      name: Schneider Electric
      #COMPANY CHANNEL as a prefix for all subscribed channels
      prefix: CC_
      training:
        link: https://schneider-electric3-pilot.csod.com/samldefault.aspx?ouid=3&returnurl=https://schneider-electric3-pilot.csod.com/LMS/LoDetails/DetailsLo.aspx?loid=
        homePageLink: https://schneider-electric3-pilot.csod.com/samldefault.aspx?ouid=3
      opportunity:
        application-name: Exchange
        link: https://uatbfo19-secommunities.cs17.force.com/opportunities/home#/Opportunity/
        user-common-limit: 500

redis:
  host: localhost
  port: 6379
  port-slave: 6380
  valid-time-millis: 3600000

---
spring:
  profiles: '!local'
  zipkin:
    base-url: http://zipkin.dev.exst.iotdo.schneider-electric.com:9411
security:
  require-ssl: true
server:
  ssl:
    enabled-protocols: TLSv1.2
    ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHEECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSAAES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSAAES128-SHA256
    key-store-type: PKCS12
    key-store: server.p12
    key-store-password:
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    hostname: ${HOSTNAME}
    prefer-ip-address: false
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/actuator/health
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/actuator/info
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
exchange:
  url: https://${exchange.hostname}
---
spring:
  profiles: '!ppr,!prod,!uat,!uat2'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      keys-to-sanitize:
