extranet:
  url:
    base: https://ecoxpert-qa.dev.se.com/
---
spring:
  profiles: prod
extranet:
  url:
    base: https://ecoxpert.se.com/
---
spring:
  profiles: local
extranet:
  auth:
    username: schneider
    password: Q8pwZ
