idms:
  host: https://sitbfo19-secommunities.cs17.force.com
  url:
    base: ${idms.host}/identity
  app-label: SchneiderElectricExchangeDev
  access-token-uri: ${idms.url.base}/services/oauth2/token
  pre-established-redirect-uri: ${exchange.url}/api/auth-service/v1/auth/oauth/authorisation
  client-authentication-scheme: form
  user-info-uri: ${idms.url.base}/services/oauth2/userinfo
  client-id: 3MVG9ahGHqp.k2_xWoKZZKzfq3vdC3Y.PA4oN3kZ6IBhv.z_0SnVOpUo242jy8tDDHYKtfqMhprNlw1moR_cP
  bfo-base-url: https://se--sitbfo19.my.salesforce.com
  technicaluser-username: schneiderelectricexchange.technicaluser@bridge-fo.com.sitbfo19
  technicaluser-access-token-uri: ${idms.bfo-base-url}/services/oauth2/token
  user-profile-base-url: ${idms.host}
  login: ${idms.url.base}/services/apexrest/App/${idms.app-label}/services/oauth2/authorize?response_type=code&client_id=${idms.client-id}&redirect_uri=${idms.pre-established-redirect-uri}&state={0}
  marketplace-login: ${idms.url.base}/services/apexrest/App/${appmarket.idms.app-label}/services/oauth2/authorize?response_type=code&client_id=${appmarket.idms.client-id}&redirect_uri=${appmarket.idms.redirect-uri}&state={0}
  logout: ${idms.url.base}/VFP_IDMS_IDPSloInit
---
spring:
  profiles: local
idms:
  pre-established-redirect-uri: ${exchange.url}/api/v1/auth/oauth/authorisation
  # Client secret can be obtain from https://schneider.atlassian.net/wiki/spaces/Exchange/pages/2271151475/Local+profile+credentials
  client-secret:
  technicaluser_password:
---
spring:
  profiles: sit
idms:
  app-label: SchneiderElectricExchangeSIT
  client-id: 3MVG9ahGHqp.k2_xWoKZZKzfq3jyzFqgk7Srrnu.tFRIN6sa3ErC3R3ZgTFkYAmT_VkIQR0HPtnwAuxpyMI7w
---
spring:
  profiles: uat
idms:
  host: https://secureidentity-uat.schneider-electric.com
  app-label: ${IDMS_APP_LABEL}
  client-id: 4d3da904e2952f7eb7a0535289b282324723c3005385441735f888c739f0b5d0a50ec600Dg0000006I2OaEAK
  bfo-base-url: https://se--uatbfo21.my.salesforce.com
  technicaluser-username: exchange.technicaluser@bridge-fo.com.uatbfo21
  user-profile-base-url: https://uatbfo21-secommunities.cs190.force.com
  login: ${idms.host}/identity/idplogin?app=${idms.app-label}&response_type=code&client_id=${idms.client-id}&redirect_uri=${idms.pre-established-redirect-uri}&state={0}
  marketplace-login: ${idms.host}/identity/idplogin?app=${appmarket.idms.app-label}&response_type=code&client_id=${appmarket.idms.client-id}&redirect_uri=${appmarket.idms.redirect-uri}&scope=openid%20refresh_token&state={0}
  logout: ${idms.user-profile-base-url}/identity/IDMS_IDPSloInit
---
spring:
  profiles: uat2
idms:
  host: https://secureidentity-uat.schneider-electric.com
  app-label: ${IDMS_APP_LABEL}
  client-id: 9510efbe13c880672016e883d213573dc80b233c03171b6ddca27a6b8fbad1841d650c00Dg0000006I2OaEAK
  bfo-base-url: https://se--uatbfo21.my.salesforce.com
  technicaluser-username: exchange.technicaluser@bridge-fo.com.uatbfo21
  user-profile-base-url: https://uatbfo21-secommunities.cs190.force.com
  login: ${idms.host}/identity/idplogin?app=${idms.app-label}&response_type=code&client_id=${idms.client-id}&redirect_uri=${idms.pre-established-redirect-uri}&state={0}
  marketplace-login: ${idms.host}/identity/idplogin?app=${appmarket.idms.app-label}&response_type=code&client_id=${appmarket.idms.client-id}&redirect_uri=${appmarket.idms.redirect-uri}&scope=openid%20refresh_token&state={0}
  logout: ${idms.user-profile-base-url}/identity/IDMS_IDPSloInit
---
spring:
  profiles: ppr
idms:
  host: https://secureidentity-preprod.schneider-electric.com
  app-label: ${IDMS_APP_LABEL}
  client-id: 797da6f44d62d1858c670afb3664eca73b564c406c6c922131087eb72ca7a9fc8a1e6400Dg0000006I3YAEA0
  bfo-base-url: https://se--preprod21.my.salesforce.com
  technicaluser-username: schneiderelectricexchange.technicaluser@bridge-fo.com.preprod21
  user-profile-base-url: https://preprod21-secommunities.cs61.force.com
  login: ${idms.host}/identity/idplogin?app=${idms.app-label}&response_type=code&client_id=${idms.client-id}&redirect_uri=${idms.pre-established-redirect-uri}&state={0}
  logout: ${idms.user-profile-base-url}/identity/VFP_IDMS_IDPSloInit
---
spring:
  profiles: prod
idms:
  host: https://secureidentity.schneider-electric.com
  app-label: ${IDMS_APP_LABEL}
  client-id: 3MVG9yZ.WNe6byQAvlJ.HwD94PeWhgo3bWP5kNjTeSvvOnOwjXwj17l.xA2j0A9hHsuZxx3rzfhrh.xBaZX21
  bfo-base-url: https://se.my.salesforce.com
  technicaluser-username: exchange.technicaluser@bridge-fo.com
