#Application was migrated to Apigee instead of IFW.
#To avoid confusing properties names can be refactored in scope of EXCH-25712. Devops afford required.
ifw:
  url:
    base: https://api.dev.se.com
  access-token-uri: ${ifw.url.base}/token
  client-authentication-scheme: query
---
spring:
  profiles: 'local'
ifw:
  client-id: #Get local credentials on https://schneider.atlassian.net/wiki/spaces/Exchange/pages/2271151475/Local+profile+credentials
  client-secret:
---
spring:
  profiles: uat,uat2
ifw:
  url:
    base: https://api.qa.se.com
---
spring:
  profiles: ppr
ifw:
  url:
    base: https://api.preprod.se.com
---
spring:
  profiles: prod
ifw:
  url:
    base: https://api.se.com
