ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 5

feign:
  hystrix.enabled: true
  client:
    config:
      default:
        logger-level: basic

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

logging:
  level:
    feign: DEBUG
---
spring:
  profiles: local,dev1,dev2,dev3,sit
feign:
  client:
    config:
      default:
        logger-level: full
