spring:
  datasource:
    url: 'jdbc:mariadb://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}?createDatabaseIfNotExist=true&autoReconnect=true${db.ssl-params}'
    port: 3306
  jpa:
    hibernate:
      ddl-auto: validate
db:
  ssl-params: '&useSSL=true&serverSslCert=rds-ca-2019-root.pem'
---
spring:
  profiles: local
  datasource:
    host: localhost
    username: root
    password: root
db:
  ssl-params:
---
spring:
  profiles: dev1
  datasource:
    host: exst-dev-mariadb-20200207170849023600000005.cbklzkym93u8.eu-west-1.rds.amazonaws.com
---
spring:
  profiles: dev2
  datasource:
    host: exst-dev2-mariadb-20200210084554123200000001.cbklzkym93u8.eu-west-1.rds.amazonaws.com
---
spring:
  profiles: dev3
  datasource:
    host: exst-dev3-mariadb-20200207151033034200000003.cbklzkym93u8.eu-west-1.rds.amazonaws.com
---
spring:
  profiles: sit
  datasource:
    host: exst-sit-mariadb-20200205182353126200000005.cbklzkym93u8.eu-west-1.rds.amazonaws.com
---
spring:
  profiles: uat
  datasource:
    host: exst-uat-mariadb-20200121130816937400000005.cbklzkym93u8.eu-west-1.rds.amazonaws.com
---
spring:
  profiles: uat2
  datasource:
    host: exst-uat2-mariadb-20191107092125222400000001.cbklzkym93u8.eu-west-1.rds.amazonaws.com
---
spring:
  profiles: ppr
  datasource:
    host: exst-ppr-mariadb-20191219125331626300000001.cbklzkym93u8.eu-west-1.rds.amazonaws.com
---
spring:
  profiles: prod
  datasource:
    host: exst-prod-mariadb-20200114143954375600000001.cbklzkym93u8.eu-west-1.rds.amazonaws.com
