server:
  port: 30125

spring:
  profiles:
    include:
      - feign
      - appmarket

federated-email-postfix: '@exchange.com'

apigee:
  org: se-exchange-dev
  url: https://api.enterprise.apigee.com/v1/organizations/${apigee.org}
  env: dev
  kvm.name: quota
  seZone: schneider-electric-seexchangeuat
  oauth:
    enabled: true
    tokenUri: https://${apigee.seZone}.login.apigee.com/oauth/token
    username: machine-se-exchange-dev@se.com
    basic:
      username: edgecli

devportal:
  base-url: ${exchange.url}/devportal
  url: ${devportal.base-url}/services/rest
  auth:
    access-token-uri: ${devportal.base-url}/oauth/token
    scope:
      - basic

analytics:
  errors:
    collapse-threshold: 12

logging:
  level:
    com.epam.apimanagement.impl.converter.quota: DEBUG

amazon:
  sqs:
    queueName: exst-${ENV_TYPE}-${ZDT_COLOR}-api-management-q.fifo
    deadLetterQueueName: exst-${ENV_TYPE}-${ZDT_COLOR}-api-management-dlq.fifo
    consumer-threads: 1

---
spring:
  profiles: 'local'
# AWS credentials can be used for local development only.
amazon:
  credentials:
    access-key: test
    secret-key: test
  sqs:
    queueName: exst-local-api-management-q.fifo
    deadLetterQueueName: exst-local-api-management-dlq.fifo
    consumer-threads: 1
apigee:
  auth:
    username: #Get local credentials on https://schneider.atlassian.net/wiki/spaces/Exchange/pages/2271151475/Local+profile+credentials
    password:
  oauth:
    password:
    basic:
      password:
devportal:
  base-url: https://exst-ui-dev.schneider-electric.com/devportal
  auth:
    username:
    password:
    client-id:
    client-secret:
