user-ail-roles-mapping:
  MP_ROLE_COMPANY_ADMIN: EXCHANGE_MP_ROLE_COMPANY_ADMIN
  MP_ROLE_BILLING_ADMIN: EXCHANGE_MP_ROLE_BILLING_ADMIN
  MP_ROLE_PUBLISHER: EXCHANGE_MP_ROLE_PUBLISHER
  MP_ROLE_USER: EXCHANGE_MP_ROLE_USER
